### ISSUE TITLE
stm32f103cbt6 no run

### ISSUE THREAD

**Issue by skylin008** [Staok/stm32_framework#2]
I had build the latest source code in project/stm32f10x-md/mdk(AC6)/stm32f10x  with stm32f103cbt6, but it can't run. The external crystal is 12Mhz and  had modified the `#define HSE_VALUE    ((uint32_t)12000000) /*!< Value of the External oscillator in Hz */` from mcu_config.h. How to solve this issue.Thanks!

**Comment by Staok** [comment]
Building STM32 project is a complex work with many steps. It is suggested to follow the professional tutorial step by step to build a project. I said in README that the code of this REPO is not suitable for directly use for now, and I haven't had time to handle  this project, so it still has many bugs, so at present, it is only suitable for experts to use it for reference and learn. Sorry
